# Generated by Django 5.2 on 2025-05-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_feedback_admin_reply_feedback_replied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
