# Generated by Django 5.2 on 2025-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_eventtype_cost_eventtype_example_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='catering',
            field=models.ManyToManyField(to='myapp.cateringoption'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='cost',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
