# Generated by Django 5.2 on 2025-05-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_eventtype_catering_alter_eventtype_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='catering',
        ),
        migrations.AddField(
            model_name='service',
            name='catering',
            field=models.ManyToManyField(to='myapp.cateringoption'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
