# Generated by Django 5.2 on 2025-05-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_eventtype_catering_service_catering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='catering',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.cateringoption'),
        ),
        migrations.DeleteModel(
            name='ContentIdea',
        ),
    ]
