# Generated by Django 5.2 on 2025-05-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_service_catering_delete_contentidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='example_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
