# Generated by Django 5.2 on 2025-05-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_eventtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='service',
            name='example_data',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='example_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
