# Generated by Django 5.2 on 2025-05-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_service_cost_remove_service_example_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='catering',
        ),
    ]
